import { Application, ApplicationItem } from './application';

export const applications: Application[] = [
  {
    id: 101,
    serviceType: 'New Water Connection',
    applicantName: 'Ahmed Hassan',
    applicantEmail: 'ahmed.hassan@email.com',
    applicantAddress: 'Male\', Maldives',
    applicantPhone: '+960 7123456',
    businessName: 'Hassan Trading',
    applicationItems: [
      new ApplicationItem('Connection Fee', 'Initial connection fee', 1, 500, 500),
      new ApplicationItem('Installation', 'Pipe installation', 1, 1500, 1500),
    ],
    applicationDate: new Date('2024-01-15'),
    totalCost: 2000,
    processingFee: 200,
    grandTotal: 2200,
    status: 'Approved',
    remarks: 'Application approved and scheduled for installation',
    completed: true,
    isSelected: false,
  },
  {
    id: 2,
    serviceType: 'Meter Replacement',
    applicantName: 'Aisha Mohamed',
    applicantEmail: 'aisha.mohamed@email.com',
    applicantAddress: 'Hulhumale\', Maldives',
    applicantPhone: '+960 7234567',
    businessName: '',
    applicationItems: [
      new ApplicationItem('Meter Unit', 'New water meter', 1, 800, 800),
      new ApplicationItem('Labor', 'Installation labor', 1, 300, 300),
    ],
    applicationDate: new Date('2024-02-10'),
    totalCost: 1100,
    processingFee: 110,
    grandTotal: 1210,
    status: 'Pending',
    remarks: 'Under review',
    completed: false,
    isSelected: false,
  },
  {
    id: 3,
    serviceType: 'Repair Request',
    applicantName: 'Mohamed Ali',
    applicantEmail: 'mohamed.ali@email.com',
    applicantAddress: 'Vilimale\', Maldives',
    applicantPhone: '+960 7345678',
    businessName: '',
    applicationItems: [
      new ApplicationItem('Pipe Repair', 'Leak repair service', 1, 600, 600),
      new ApplicationItem('Materials', 'Repair materials', 1, 200, 200),
    ],
    applicationDate: new Date('2024-02-20'),
    totalCost: 800,
    processingFee: 80,
    grandTotal: 880,
    status: 'In Progress',
    remarks: 'Technician assigned',
    completed: false,
    isSelected: false,
  },
  {
    id: 4,
    serviceType: 'Billing Inquiry',
    applicantName: 'Fatima Ibrahim',
    applicantEmail: 'fatima.ibrahim@email.com',
    applicantAddress: 'Male\', Maldives',
    applicantPhone: '+960 7456789',
    businessName: 'Ibrahim General Store',
    applicationItems: [],
    applicationDate: new Date('2024-02-21'),
    totalCost: 0,
    processingFee: 0,
    grandTotal: 0,
    status: 'Resolved',
    remarks: 'Billing query resolved',
    completed: true,
    isSelected: false,
  },
];
