import { ServiceDirectory } from './service-directory';

export const serviceDirectoryList: ServiceDirectory[] = [
  {
    Id: 1,
    serviceType: 'primary',
    serviceCategory: 'Water Supply',
    serviceName: 'New Water Connection',
    description: 'Apply for a new water connection service',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 01 Jan 2026',
    bg_color: 'error',
    icon: 'chart-bubble',
    color: 'text-error',
  },
  {
    Id: 2,
    serviceType: 'success',
    serviceCategory: 'Billing',
    serviceName: 'Bill Payment',
    description: 'Pay your water bills online',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 05 Jan 2026',
      bg_color: 'primary',
      icon: 'building-store',
      color: 'text-primary',
  },
  {
    Id: 3,
    serviceType: 'warning',
    serviceCategory: 'Maintenance',
    serviceName: 'Repair Request',
    description: 'Request repair for water supply issues',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 10 Jan 2026',
        bg_color: 'error',
    icon: 'chart-bubble',
    color: 'text-error',
  },
  {
    Id: 4,
    serviceType: 'error',
    serviceCategory: 'Account',
    serviceName: 'Account Management',
    description: 'Manage your account details',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 15 Jan 2026',
    bg_color: 'secondary',
      icon: 'category-2',
      color: 'text-secondary',
  },
  {
    Id: 5,
    serviceType: 'primary',
    serviceCategory: 'Support',
    serviceName: 'Customer Support',
    description: 'Get help from our support team',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 20 Jan 2026',
         bg_color: '--mat-sys-outline-variant',
      icon: 'activity-heartbeat',
      color: 'text-dark',
  },
  {
    Id: 6,
    serviceType: 'secondary',
    serviceCategory: 'Reports',
    serviceName: 'Usage Reports',
    description: 'View your water usage reports',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 25 Jan 2026',
    bg_color: 'secondary',
      icon: 'category-2',
      color: 'text-secondary',
  },
];
  export const stats = [
    {
      id: 1,
      label: 'Expert Advisor',
      description: 'Suspendisse vestibulum eu erat ac scelerisque.',
      bg_color: 'error',
      icon: 'chart-bubble',
      color: 'text-error',
    },
    {
      id: 2,
      label: 'Effective Support',
      description: 'Suspendisse vestibulum eu erat ac scelerisque.',
      bg_color: 'primary',
      icon: 'building-store',
      color: 'text-primary',
    },
    {
      id: 3,
      label: 'Low Fees',
      description: 'Suspendisse vestibulum eu erat ac scelerisque.',
      bg_color: 'secondary',
      icon: 'category-2',
      color: 'text-secondary',
    },
    {
      id: 4,
      label: 'Loan Facility',
      description: 'Suspendisse vestibulum eu erat ac scelerisque.',
      bg_color: '--mat-sys-outline-variant',
      icon: 'activity-heartbeat',
      color: 'text-dark',
    },
  ];
