import { ServiceDirectory } from './service-directory';

export const serviceDirectoryList: ServiceDirectory[] = [
  {
    Id: 1,
    serviceType: 'primary',
    serviceCategory: 'Water Supply',
    serviceName: 'New Water Connection',
    description: 'Apply for a new water connection service',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 01 Jan 2026',
  },
  {
    Id: 2,
    serviceType: 'success',
    serviceCategory: 'Billing',
    serviceName: 'Bill Payment',
    description: 'Pay your water bills online',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 05 Jan 2026',
  },
  {
    Id: 3,
    serviceType: 'warning',
    serviceCategory: 'Maintenance',
    serviceName: 'Repair Request',
    description: 'Request repair for water supply issues',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 10 Jan 2026',
  },
  {
    Id: 4,
    serviceType: 'error',
    serviceCategory: 'Account',
    serviceName: 'Account Management',
    description: 'Manage your account details',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 15 Jan 2026',
  },
  {
    Id: 5,
    serviceType: 'primary',
    serviceCategory: 'Support',
    serviceName: 'Customer Support',
    description: 'Get help from our support team',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 20 Jan 2026',
  },
  {
    Id: 6,
    serviceType: 'secondary',
    serviceCategory: 'Reports',
    serviceName: 'Usage Reports',
    description: 'View your water usage reports',
    provider: 'MWSC',
    status: 'Active',
    lastUpdated: 'Updated 25 Jan 2026',
  },
];
